// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[document].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/api/gallery/[name].ts";
import * as $$0 from "./islands/Gallery.tsx";
import * as $$1 from "./islands/Globe.tsx";
import * as $$2 from "./islands/LightBox.tsx";
import * as $$3 from "./islands/Map.tsx";
import * as $$4 from "./islands/Navigation.tsx";
import * as $$5 from "./islands/PlaceDetails.tsx";

const manifest = {
  routes: {
    "./routes/[document].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/api/gallery/[name].ts": $2,
  },
  islands: {
    "./islands/Gallery.tsx": $$0,
    "./islands/Globe.tsx": $$1,
    "./islands/LightBox.tsx": $$2,
    "./islands/Map.tsx": $$3,
    "./islands/Navigation.tsx": $$4,
    "./islands/PlaceDetails.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
