// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_document_ from "./routes/[document].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_gallery_name_ from "./routes/api/gallery/[name].ts";
import * as $Globe from "./islands/Globe.tsx";
import * as $LightBox from "./islands/LightBox.tsx";
import * as $Map from "./islands/Map.tsx";
import * as $Navigation from "./islands/Navigation.tsx";
import * as $PlaceDetails from "./islands/PlaceDetails.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[document].tsx": $_document_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/gallery/[name].ts": $api_gallery_name_,
  },
  islands: {
    "./islands/Globe.tsx": $Globe,
    "./islands/LightBox.tsx": $LightBox,
    "./islands/Map.tsx": $Map,
    "./islands/Navigation.tsx": $Navigation,
    "./islands/PlaceDetails.tsx": $PlaceDetails,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
